### PR TITLE
Develop

### LINKED ISSUE #18: RepositoryConnection.export(handler, graphs) ignores contexts
See code
```

 public void export(RDFHandler handler, Resource... contexts) throws RepositoryException, RDFHandlerException {
        exportStatements(null, null, null, true, handler);
    }
```
This causes quite some problems because when we use export the whole store gets exported.

### PR DESCRIPTION
**Pull request by akshaysonvane**
Version update from 1.0.0 to 1.1.0
Expose Transaction object.
Fixes #18 export now uses the supplied contexts and returns only explicit statements.

### CODE REVIEW

File: marklogic-rdf4j/src/test/java/com/marklogic/semantics/rdf4j/MarkLogicRepositoryTransactionTest.java [hunk 1]
```diff
@@ -190,4 +197,31 @@ public void testMultipleCommit()
...
+        DocumentManager docMgr = adminClient.newDocumentManager();
+        String docId = "/tx-rollback/bbq1.xml";
+        FileHandle handle = new FileHandle(file);
+        handle.set(file);
+        handle.setFormat(Format.XML);
+        docMgr.write(docId, handle, conn.getTransaction());
+        DocumentDescriptor documentDescriptor = docMgr.exists(docId, conn.getTransaction());
+        Assert.assertEquals(docId, documentDescriptor.getUri());
+        Assert.assertNull(docMgr.exists(docId));
+        conn.rollback();
```
Comment (grechaw) [inline marklogic-rdf4j/src/test/java/com/marklogic/semantics/rdf4j/MarkLogicRepositoryTransactionTest.java]: I think this needs just two more assertions.  After the rollback, con.getTransaction() should be null (yes?) and the document must not exist, just like in line 224.  After that this test will be all good.
